version: '3.7'

services:
  node:
    container_name: omnixent-node
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    restart: unless-stopped
    links:
      - redis
    environment:
      - REDIS_URL=redis://cache
    networks:
      - caddynet

  caddy:
    image: abiosoft/caddy
    container_name: omnixent-caddy
    cap_add:
      - CAP_NET_BIND_SERVICE
    ports:
      - 9010:9010
      - 9011:9011
    expose:
      - 9010
      - 9011
    links:
      - node
    depends_on:
      - node
    volumes:
      - ./Caddyfile:/etc/Caddyfile
    command: -conf /etc/Caddyfile
    environment:
      CA_URL: https://acme-staging-v02.api.letsencrypt.org/directory
    restart: always
    networks:
      - caddynet

    redis:
      image: "redis:alpine"
      container_name: omnixent-cache
      expose:
        - 6379

networks:
  caddynet:
    driver: bridge
